apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: carsten-e2e-pipeline
  app.kubernetes.io/instance: carsten-e2e-pipeline-instance
  app.kubernetes.io/name: carsten-e2e-pipeline
images:
- name: '*'
  newName: quay.io/carstenmichel/carsten-next-app
  newTag: 62aa32beaddf27496ca9c7e1555c4db122a599bf
