apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: e2e-next-app
  app.kubernetes.io/instance: e2e-next-app-instance
  app.kubernetes.io/name: e2e-next-app
images:
- name: '*'
  newName: quay.io/carstenmichel/carsten-next-app
  newTag: 62aa32beaddf27496ca9c7e1555c4db122a599bf
